
name: 🐞 Bug
description: Arquivo para retorpar um BUG
title: "fix: "
labels: [fix, bug, triage]
assignees:
  - PaoloProdossimoLopes
body:
- type: markdown
  attributes:
    value: |
      Obrigado por ter um separado um tempo para preencher o reporte

- type: checkboxes
  attributes:
    label: Ainda não existe uma "issue" ja aberta para esse problema ?
    description: Certifique-se que ainda não existe um problema semelhante repotado antes de abrir um novo.
    options:
      - label: Eu procurei se existe ja uma "issue" para o meu problema
        required: true

- type: input
  id: contact
  attributes:
    label: Detalhes para contato
    description: Onde podemos entrar em contato para caso precisemos de mais informações?
    placeholder: ex. email@example.com
  validations:
    required: false

- type: textarea
  attributes:
    label: Comportamento atual
    description: Descreva brevemente qual o problema encontrado ...
    placeholder: Ao tentar fazer operaçao X ocorre o problema Y
  validations:
    required: true

- type: textarea
  attributes:
    label: Comportamento esperado
    description: Descreva brevemente qual o comportamento esperado...
    placeholder: Ao tentar fazer operaçao X deveria ocorrer o comportamento Z
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Sistema operacional
    description: Qual sistema operacional esta usando ?
    placeholder: 'ex: macOS Big Sur'
  validations:
    required: true

- type: checkboxes
  id: operating-systems
  attributes:
    label: Em qual dos browsers você notou o problema ?
    description: Selecione qual você utilizou.
    options:
      - label: Safari
      - label: Chrome
      - label: firefox
      - label: Opera
      - label: Brave
      - label: Edge
      - label: Outro

- type: textarea
  id: logs
  attributes:
    label: Logs relevantes
    description: Copie e cole (ou arraste) qualquer log que julge relevante para a analise pro problema.
    render: Shell
  validations:
    required: false
    
- type: checkboxes
  id: terms
  attributes:
    label: Codigo de conduta
    description: Para enviar o reporte, você precisa aceitar os seguinte [codigo de conduta](https://opensource.guide/code-of-conduct/#:~:text=A%20code%20of%20conduct%20is,social%20atmosphere%20for%20your%20community.)
    options:
      - label: Eu aceito o codigo de conduta do projeto.
        required: true

- type: markdown
  attributes:
    value: "Thanks for completing our form!"
