name: 💡 Feature
description: Arquivo para retorpar uma feature
title: "feat: "
labels: [feature, enhancement, triage]
assignees:
  - PaoloProdossimoLopes
body:
- type: markdown
  attributes:
    value: |
      Obrigado por ter um separado um tempo para preencher o reporte
